Repository muskanchoudhary001/my-ToDo-List, pull requests merged in 2022-10, with the labels that each got.

#1 accept kar musky don..
  ToDolist.html
Labels: hacktober, hacktoberfest2022

#2 accept kar re moti muskii
  ToDolist.html
Labels: hacktober, hacktoberfest2022

#3 updated file
  ToDolist.html
Labels: hacktober, hacktoberfest2022, hacktoberfest

#4 Update ToDolist.html
  ToDolist.html
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accept

#5 Update ToDolist.html
  ToDolist.html
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accept

#6 Update ToDolist.html
  ToDolist.html
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accept

#7 updated file
  ToDolist.html
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accept

#8 Update ToDolist.html
  ToDolist.html
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accept

#9 Update ToDolist.html
  ToDolist.html
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accept

#10 updated CSS file
  ToDolist.html
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accept

#11 updated code
  ToDolist.html
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accept

#14 Update ToDolist.html
  ToDolist.html
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accept
